
while (true) fun foo() {} // error: unexpected fun
